### ISSUE TITLE
Problema de migracion 

### ISSUE THREAD

**Issue by adolfobarrossomerson** [carloshernan007/ifces#1]
No he podido añadir bien las tablas de la base de datos debido a que el orden de las actualizaciones ya no son las mismas y por tal motivo salen errores

![prueba](https://github.com/carloshernan007/icfes/assets/104148461/4558d79f-c4ef-4455-bb13-dc2a46d50262)

**Comment by carloshernan007** [comment]
Vale, trabaje en este tema gracias por reportarlo

**Comment by carloshernan007** [comment]
Solucionado, por favor baja los cambios 
![image](https://github.com/carloshernan007/icfes/assets/1942655/6ed8741c-b4a9-4707-aabd-ee54333aae81)

**Comment by carloshernan007** [comment]
Verificado
