### ISSUE TITLE
Problema con la migración

### ISSUE THREAD

**Issue by ingluisgarcia** [carloshernan007/ifces#2]
Hola, he estado siguiendo las instrucciones del proyecto y al momento de realizar la migración a la base de datos, me aparece el siguiente error: 
![Captura de pantalla 2024-06-29 110019](https://github.com/carloshernan007/icfes/assets/4211294/970a856e-8bac-4787-a1e0-3bf95001eda5)

**Comment by carloshernan007** [comment]
Solucionado en el commit: 80026b010c80eab1478187678cf61b9a5f17cd3b
![Captura desde 2024-06-30 17-20-43](https://github.com/carloshernan007/icfes/assets/1942655/ac1f9e97-6e7b-474e-a197-1e066f423fc1)

**Comment by carloshernan007** [comment]
Ok
